### ISSUE TITLE
Processor stops listening further events after uncaught exceptions/errors

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/legacy-challenge-resource-processor#13]
From the logs of the processor it seems it stops processing new events once it fails because of any uncaught exception/error:

```
07:39:49 { Error: cannot POST /v5/bus/events (504)
07:39:49 at Response.toError (/legacy-resources-processor/node_modules/topcoder-bus-api-wrapper/node_modules/superagent/lib/node/response.js:94:15)
07:39:49 at ResponseBase._setStatusProperties (/legacy-resources-processor/node_modules/topcoder-bus-api-wrapper/node_modules/superagent/lib/response-base.js:123:16)
07:39:49 at new Response (/legacy-resources-processor/node_modules/topcoder-bus-api-wrapper/node_modules/superagent/lib/node/response.js:41:8)
07:39:49 at Request._emitResponse (/legacy-resources-processor/node_modules/topcoder-bus-api-wrapper/node_modules/superagent/lib/node/index.js:752:20)
07:39:49 at IncomingMessage.parser (/legacy-resources-processor/node_modules/topcoder-bus-api-wrapper/node_modules/superagent/lib/node/index.js:916:38)
07:39:49 at IncomingMessage.emit (events.js:194:15)
07:39:49 at endReadableNT (_stream_readable.js:1125:12)
07:39:49 at process._tickCallback (internal/process/next_tick.js:63:19)
07:39:49status: 504,
07:39:49 text:
07:39:49 '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n',
07:39:49 method: 'POST',
07:39:49 path: '/v5/bus/events' },
```

fyi @rootelement @ThomasKranitsas

**Comment by lakshmiathreya** [comment]
@vikasrohit is this issue resolved now? could you close it if so? thx!

**Comment by vikasrohit** [comment]
I am not sure about it @lakshmiathreya I observed this behaviour, so reported it. May be @rootelement or @ThomasKranitsas can better decide if they want to keep it for tracking purposes or close it.
